import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import ResponsiveAppBar from "@/components/ResponsiveAppBar/ResponsiveAppBar";
import ArgumentationSection from "@/pages-sections/argumentation-section/argumentationSection";
import LandingpageSection from "@/pages-sections/landingpage-section/LandingpageSection";
import ExpertSection from "@/pages-sections/expert-section/ExpertSection";
import BenefitSection from "@/pages-sections/benefit-section/BenefitSection";
import ProjectSection from "@/pages-sections/project-section/ProjectSection";
import StepsSection from "@/pages-sections/steps-section/StepsSection";
import CompetenceSection from "@/pages-sections/competence-section/CompetenceSection";
import CtaSection from "@/pages-sections/cta-section/CtaSection";
import FooterSection from "@/pages-sections/footer-section/FooterSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>PIRI WEB</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='viewport' content='initial-scale=1, width=device-width' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ResponsiveAppBar />
      <LandingpageSection />
      <ArgumentationSection />
      <ExpertSection />
      <BenefitSection />
      <ProjectSection />
      <StepsSection />
      <CompetenceSection />
      <CtaSection />
      <FooterSection />
    </>
  );
}
